language: node_js
node_js:
  - "9"

before_install:
  - sudo apt-get install -y libav-tools

script:
  - npm run build
  - npm run playlists
  - npm run favicons

deploy:
  provider: surge
  project: ./dist/
  domain: https://radiocloud.surge.sh
  skip_cleanup: true
